# Generated by Django 3.0 on 2019-12-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10000),
        ),
    ]
