# Generated by Django 3.0 on 2019-12-14 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbooks', '0002_auto_20191213_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbook',
            name='featured',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
